#!/bin/bash

read -r -d '' USAGE <<'EOF'
Usage: build-deb [-n project_name]
Example: build-deb
Example: build-deb -n mobnode-testbuild
EOF

NODE_PROJECT=mobboss
RELEASE=
PROJECT_DIR=

while getopts n: opt; do
  case $opt in
    n)
      NODE_PROJECT="$OPTARG"
      PROJECT_DIR="$NODE_PROJECT`date +%Y%m%d%H%M`"
      ;;
    \?)
      echo "${USAGE}" >&2
      exit 1
      ;;
    esac
done

NPM_ENV="client/.env.default"
if [ -e $NPM_ENV ]; then
  if ! grep -q REACT_APP_TAG $NPM_ENV; then
    echo "REACT_APP_TAG must be in $NPM_ENV" >&2
    exit 2
  fi
  RELEASE=`grep REACT_APP_TAG $NPM_ENV | awk -F "=" '{print $2}' | tr -d '"'` 
  #RELEASE=`grep REACT_APP_TAG $NPM_ENV | awk -F "=" '{print $2}' | tr -d '"' | awk -F "-" '{print $2}'`
  if [ -z "$RELEASE" ]; then
    echo "Cannot determine release value from REACT_APP_TAG" >&2
    exit 3
  fi
else
  echo "$NPM_ENV must exist and contain REACT_APP_TAG" >&2
  exit 4
fi

echo $RELEASE

mkdir ~/debs
sudo rm -r ~/debs/mobboss
mkdir -p ~/debs/mobboss/etc/systemd/system

echo "[Unit]
Description=
After=network.target nss-lookup.target

[Service]
ExecStart=/usr/bin/npm start
WorkingDirectory=/usr/lib/mobboss
Restart=always
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=mobboss
User=root

[Install]
WantedBy=multi-user.target
" >> ~/debs/mobnode/etc/systemd/system/mobboss.service

mkdir -p ~/debs/mobboss/usr/lib
cd ..
cp -r mobboss ~/debs/mobboss/usr/lib/mobboss
cd ~/debs
mkdir mobboss/DEBIAN
echo "Package: Mobboss
Architecture: all
Maintainer: mobdata
Depends:
Priority: optional
Version: $RELEASE
Description: Mobdata app for monitoring nodes and replication" >> mobboss/DEBIAN/control

sudo chown -R root:root mobboss
 
sudo dpkg-deb --build mobboss

echo "package built int ~/debs"






